#ifndef COMMON_COLONY_CONFIG_H_
#define COMMON_COLONY_CONFIG_H_

// Enable trace
#define USE_CPL_SYSTEM_TRACE

// CLI
#define OPTION_CPL_TSHELL_PROCESSOR_INPUT_SIZE      (8*1024)
#define OPTION_CPL_TSHELL_PROCESSOR_OUTPUT_SIZE     (8*1024)
#define OPTION_CPL_TSHELL_PROCESSOR_PROMPT          "$$$ "

// Data Model
#define OPTION_CPL_DM_MODEL_DATABASE_MAX_CAPACITY_JSON_DOC  (8*1024)
#define OPTION_CPL_DM_MODEL_DATABASE_TEMP_STORAGE_SIZE      (8*1024)


#endif
