#ifndef COLONY_CONFIG_H_
#define COLONY_CONFIG_H_

// Enable Test B
#define BUILD_TEST_B_

// Enable Trace
#define USE_CPL_SYSTEM_TRACE

// Load fonts...
//#define USE_BSP_GLCD_ENABLE_FONT_HELVR10
//#define USE_BSP_GLCD_ENABLE_FONT_8X8
//#define USE_BSP_GLCD_ENABLE_FONT_8X16
//#define USE_BSP_GLCD_ENABLE_FONT_LARGE_SYSTEM
//#define USE_BSP_GLCD_ENABLE_FONT_6X13



#endif
